name: PR Labels

on: [pull_request]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  size-label:
    name: PR size labels
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

