name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: checkout
      uses: actions/checkout@v2
    - name: download dependencies
      run: go get -v -t -d ./...
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: validate
      run: make validate
    - name: build
      run: make build
